<?php
// Prompt for Tamil,Sinhala ....
global $Prompt ;

$Prompt[""]["EN"]  =  "";
$Prompt[""]["TM"]  =  "";
$Prompt[""]["SL"]  =  "";

$Prompt["OutCome"]["EN"]  =  "OutCome";
$Prompt["OutCome"]["TM"]  =  "விளைவு";
$Prompt["OutCome"]["SL"]  =  "ප්‍රතිඑලය";

$Prompt["Refer To"]["EN"]  =  "Refer To";
$Prompt["Refer To"]["TM"]  =  "தொடர்புபடுத்தல்";
$Prompt["Refer To"]["SL"]  =  "සම්බන්ධය කිරීම";

$Prompt["Discharge Remarks"]["EN"]  =  "Discharge Remarks";
$Prompt["Discharge Remarks"]["TM"]  =  "விலக்களிப்புக்கான குறிப்பு";
$Prompt["Discharge Remarks"]["SL"]  =  "අස් කිරීමේ විස්තරය";

$Prompt["Diagnosis"]["EN"]  =  "Diagnosis";
$Prompt["Diagnosis"]["TM"]  =  "நோய் அறிகுறி";
$Prompt["Diagnosis"]["SL"]  =  "රෝග විනිශ්චය";

$Prompt["Diagnosis entry date"]["EN"]  =  "Diagnosis entry date";
$Prompt["Diagnosis entry date"]["TM"]  =  "நோய் அறிகுறி ஆரம்பிக்கப்பட்ட திகதி";
$Prompt["Diagnosis entry date"]["SL"]  =  "රෝග විනිශ්චය ආරම්භ කල දිනය";

$Prompt["ICD Diagnosis"]["EN"]  =  "ICD Diagnosis";
$Prompt["ICD Diagnosis"]["TM"]  =  "ICD நோய் அறிகுறி";
$Prompt["ICD Diagnosis"]["SL"]  =  "ICD රෝග විනිශ්චය";

$Prompt["SNOMED Diagnosis"]["EN"]  =  "SNOMED Diagnosis";
$Prompt["SNOMED Diagnosis"]["TM"]  =  "SNOMED நோய் அறிகுறி";
$Prompt["SNOMED Diagnosis"]["SL"]  =  "SNOMED රෝග විනිශ්චය";

$Prompt["IMMR Diagnosis"]["EN"]  =  "IMMR Diagnosis";
$Prompt["IMMR Diagnosis"]["TM"]  =  "IMMR நோய் அறிகுறி";
$Prompt["IMMR Diagnosis"]["SL"]  =  "IMMR රෝග විනිශ්චය";

$Prompt["Procedures"]["EN"]  =  "Procedures";
$Prompt["Procedures"]["TM"]  =  "செயல் முறைகள்";
$Prompt["Procedures"]["SL"]  =  "ක්‍රියා පරිපාටිය";

$Prompt["Procedure entry date"]["EN"]  =  "Procedure entry date";
$Prompt["Procedure entry date"]["TM"]  =  "செயல்முறை ஆரம்பிக்கப்பட்ட திகதி";
$Prompt["Procedure entry date"]["SL"]  =  "ක්‍රියා පරිපාටිය ආරම්භ කල දිනය";

$Prompt["Surgical procedures"]["EN"]  =  "Surgical procedures";
$Prompt["Surgical procedures"]["TM"]  =  "அறுவை சிகிச்சை செயல் முறைகள்";
$Prompt["Surgical procedures"]["SL"]  =  "ශල්‍යකර්මයට ක්‍රියා පරිපාටිය";

$Prompt["Notes"]["EN"]  =  "Notes";
$Prompt["Notes"]["TM"]  =  "குறிப்பு";
$Prompt["Notes"]["SL"]  =  "විස්තරය";

$Prompt["Discharge"]["EN"]  =  "Discharge";
$Prompt["Discharge"]["TM"]  =  "விலக்களித்தல்";
$Prompt["Discharge"]["SL"]  =  "අස් කිරීම";

$Prompt["Discharge"]["EN"]  =  "Discharge";
$Prompt["Discharge"]["TM"]  =  "விலக்களித்தல்";
$Prompt["Discharge"]["SL"]  =  "අස් කිරීම";

$Prompt["Discharge patient"]["EN"]  =  "Discharge patient";
$Prompt["Discharge patient"]["TM"]  =  "நோயாளியை விலக்களித்தல்";
$Prompt["Discharge patient"]["SL"]  =  "රෝගියාව අස් කිරීම";

$Prompt["Discharge ICD"]["EN"]  =  "Discharge ICD";
$Prompt["Discharge ICD"]["TM"]  =  "ICD விலக்களித்தல்";
$Prompt["Discharge ICD"]["SL"]  =  "ICD අස් කිරීම";

$Prompt["Discharge SNOMED"]["EN"]  =  "Discharge SNOMED";
$Prompt["Discharge SNOMED"]["TM"]  =  "SNOMED விலக்களித்தல்";
$Prompt["Discharge SNOMED"]["SL"]  =  "SNOMED අස් කිරීම";

$Prompt["Discharge IMMR"]["EN"]  =  "Discharge IMMR";
$Prompt["Discharge IMMR"]["TM"]  =  "IMMR விலக்களித்தல்";
$Prompt["Discharge IMMR"]["SL"]  =  "IMMR අස් කිරීම";

$Prompt["Ward transfer"]["EN"]  =  "Ward transfer";
$Prompt["Ward transfer"]["TM"]  =  "விடுதி மாற்றம்";
$Prompt["Ward transfer"]["SL"]  =  "වාට්ටුව මාරු කිරීම";

$Prompt["Patient Transfer"]["EN"]  =  "Patient Transfer";
$Prompt["Patient Transfer"]["TM"]  =  "நோயாளியை மாற்றம் செய்தல்";
$Prompt["Patient Transfer"]["SL"]  =  "රෝගියාව මාරු කිරීම";

$Prompt["BHT"]["EN"]  =  "BHT";
$Prompt["BHT"]["TM"]  =  "கட்டில் சிட்டை இல";
$Prompt["BHT"]["SL"]  =  "ඇඳ ඉහපත් අංකය";

$Prompt["Initial admission details"]["EN"]  =  "Initial admission details";
$Prompt["Initial admission details"]["TM"]  =  "ஆரம்ப அனுமதி தொடர்பான தகவல்";
$Prompt["Initial admission details"]["SL"]  =  "ආරම්භක අනුමත පිළිබඳ තොරතුරු";

$Prompt["Quantity"]["EN"]  =  "Quantity";
$Prompt["Quantity"]["TM"]  =  "அளவு";
$Prompt["Quantity"]["SL"]  =  "ප්‍රමාණය";

$Prompt["Last Accessed By"]["EN"]  =  "Last Accessed By";
$Prompt["Last Accessed By"]["TM"]  =  "கடைசியாக பயன்படுத்தியவர்";
$Prompt["Last Accessed By"]["SL"]  =  "අන්තිමට නිර්මිත කළ පුද්ගලයා";

$Prompt["Sample collection Date"]["EN"]  =  "Sample collection Date";
$Prompt["Sample collection Date"]["TM"]  =  "மாதிரி சேகரிக்கப்பட்ட திகதி";
$Prompt["Sample collection Date"]["SL"]  =  "සාම්පලය එකතු කළ දිනය";

$Prompt["Result"]["EN"]  =  "Result";
$Prompt["Result"]["TM"]  =  "முடிவுகள்";
$Prompt["Result"]["SL"]  =  "ප්‍රතිඑලය";

$Prompt["Result confirmed by"]["EN"]  =  "Result confirmed by";
$Prompt["Result confirmed by"]["TM"]  =  "முடிவுகள் உறுதிப்படுத்தப்பட்டது";
$Prompt["Result confirmed by"]["SL"]  =  "තහවුරු කළ ප්‍රතිඑලය";

$Prompt["Reference"]["EN"]  =  "Reference";
$Prompt["Reference"]["TM"]  =  "குறிப்பு";
$Prompt["Reference"]["SL"]  =  "සටහන";

$Prompt["Permission"]["EN"]  =  "Permission";
$Prompt["Permission"]["TM"]  =  "அனுமதி";
$Prompt["Permission"]["SL"]  =  "අවසරය";

$Prompt["Procedure Room"]["EN"]  =  "Procedure Room";
$Prompt["Procedure Room"]["TM"]  =  "செயல்முறை அறை";
$Prompt["Procedure Room"]["SL"]  =  "ක්‍රියා පරිපාටි කාමරය";

$Prompt["Number"]["EN"] = "Number";
$Prompt["Number"]["TM"] = "இல";
$Prompt["Number"]["SL"] = "අංකය";

$Prompt["Patient Visit Information"]["EN"]  =  "Patient Visit Information";
$Prompt["Patient Visit Information"]["TM"]  =  "நோயாளியின் வருகை பற்றிய தகவல்";
$Prompt["Patient Visit Information"]["SL"]  =  "රෝගියාගේ පැමිණීමේ තොරතුරු";

$Prompt["Test "]["EN"]  =  "Test ";
$Prompt["Test "]["TM"]  =  "பரிசோதனை";
$Prompt["Test "]["SL"]  =  "පරීක්ෂණය";

$Prompt["Sex"]["EN"]  =  "Sex";
$Prompt["Sex"]["TM"]  =  "பால்";
$Prompt["Sex"]["SL"]  =  "ස්ත්‍රී/පුරුෂ භාවය";

$Prompt["Sex/Age"]["EN"]  =  "Sex/Age";
$Prompt["Sex/Age"]["TM"]  =  "பால்/வயது";
$Prompt["Sex/Age"]["SL"]  =  "ස්ත්‍රී/පුරුෂ භාවය / වයස";

$Prompt["Priority"]["EN"]  =  "Priority";
$Prompt["Priority"]["TM"]  =  "முன்னுரிமை";
$Prompt["Priority"]["SL"]  =  "ප්‍රමුඛත්වය";

$Prompt["Weight in Kg"]["EN"]  =  "Weight in Kg";
$Prompt["Weight in Kg"]["TM"]  =  "நிறை Kg";
$Prompt["Weight in Kg"]["SL"]  =  "බර Kg";

$Prompt["Height in M"]["EN"]  =  "Height in M";
$Prompt["Height in M"]["TM"]  =  "உயரம் M";
$Prompt["Height in M"]["SL"]  =  "උස M";

$Prompt["Temperature in 'c"]["EN"]  =  "Temperature in 'c";
$Prompt["Temperature in 'c"]["TM"]  =  "வெட்ப நிலை 'c";
$Prompt["Temperature in 'c"]["SL"]  =  "උෂ්ණත්වය 'c";

$Prompt["Examination"]["EN"]  =  "Examination";
$Prompt["Examination"]["TM"]  =  "பரிசோதனை";
$Prompt["Examination"]["SL"]  =  "පරීක්ෂණය";

$Prompt["Examinations"]["EN"]  =  "Examinations";
$Prompt["Examinations"]["TM"]  =  "பரிசோதனை";
$Prompt["Examinations"]["SL"]  =  "පරීක්ෂණය";

$Prompt["Examination Date"]["EN"]  =  "Examination Date";
$Prompt["Examination Date"]["TM"]  =  "பரிசோதனை திகதி";
$Prompt["Examination Date"]["SL"]  =  "පරීක්ෂණ දිනය";

$Prompt["District"]["EN"]  =  "District";
$Prompt["District"]["TM"]  =  "மாவட்டம்";
$Prompt["District"]["SL"]  =  "දිස්ත්‍රික්කය";

$Prompt["DSDivision"]["EN"]  =  "DSDivision";
$Prompt["DSDivision"]["TM"]  =  "பிரதேசசபை";
$Prompt["DSDivision"]["SL"]  =  "ප්‍රාදේශීය සභාව";

$Prompt["GNDivision"]["EN"]  =  "GNDivision";
$Prompt["GNDivision"]["TM"]  =  "கிராம சேவகர் பிரிவு ";
$Prompt["GNDivision"]["SL"]  =  "ග්‍රාම නිලධාරී අංශය";

$Prompt["Telephone"]["EN"]  =  "Telephone";
$Prompt["Telephone"]["TM"]  =  "தொலைபேசி";
$Prompt["Telephone"]["SL"]  =  "දුරකථනය";

$Prompt["BedCount"]["EN"]  =  "BedCount";
$Prompt["BedCount"]["TM"]  =  "கட்டில் எண்ணிக்கை";
$Prompt["BedCount"]["SL"]  =  "සයනයන් එකතුව";

$Prompt["Nos.Bed"]["EN"]  =  "Nos.Bed";
$Prompt["Nos.Bed"]["TM"]  =  "கட்டில் எண்ணிக்கை";
$Prompt["Nos.Bed"]["SL"]  =  "සයනයන් එකතුව";

$Prompt["Ref. Value"]["EN"]  =  "Ref. Value";
$Prompt["Ref. Value"]["TM"]  =  "மதிப்பீடு";
$Prompt["Ref. Value"]["SL"]  =  "වටිනාකම";

$Prompt["Test"]["EN"] = "Test";
$Prompt["Test"]["TM"] = "பரிசோதனை";
$Prompt["Test"]["SL"] = "පරික්ෂණ";

$Prompt["Department"]["EN"] = "Department";
$Prompt["Department"]["TM"] = "இலாகா";
$Prompt["Department"]["SL"] = "අංශය";

$Prompt["Type"]["EN"]  =  "Type";
$Prompt["Type"]["TM"]  =  "வகை";
$Prompt["Type"]["SL"]  =  "වර්ගය";

$Prompt["ICD Links"]["EN"]  =  "ICD Links";
$Prompt["ICD Links"]["TM"]  =  "ICD தொடர்பு";
$Prompt["ICD Links"]["SL"]  =  "ICD සම්බන්ටය";

$Prompt["Category"]["EN"]  =  "Category";
$Prompt["Category"]["TM"]  =  "பிரிவு";
$Prompt["Category"]["SL"]  =  "ජාතිය";

$Prompt["Notifiable"]["EN"]  =  "Notifiable";
$Prompt["Notifiable"]["TM"]  =  "அறிவிக்கவேண்டிய நோய்";
$Prompt["Notifiable"]["SL"]  =  "දැනුම් දියයුතු ලෙඩ";

$Prompt["Notifications"]["EN"]  =  "Notifications";
$Prompt["Notifications"]["TM"]  =  "அறிவிப்பு";
$Prompt["Notifications"]["SL"]  =  "දැනුම්දීම";

$Prompt["Code"]["EN"]  =  "Code";
$Prompt["Code"]["TM"]  =  "குறியீடு";
$Prompt["Code"]["SL"]  =  "සංකේත අංකය";

//terms
$Prompt["CONCEPTID"]["EN"]  =  "CONCEPTID";
$Prompt["CONCEPTID"]["TM"]  =  "கருத்து இல";
$Prompt["CONCEPTID"]["SL"]  =  "විකල්ප අංකය";

$Prompt["TERM"]["EN"]  =  "TERM";
$Prompt["TERM"]["TM"]  =  "சொல்";
$Prompt["TERM"]["SL"]  =  "පදය";

$Prompt["Canned text"]["EN"] = "Canned text";
$Prompt["Canned text"]["TM"] = "சொற்களின் சுருக்கம்";
$Prompt["Canned text"]["SL"] = "කෙටි සටහන";

//action translations
$Prompt["Treatments"]["EN"]  =  "Treatments";
$Prompt["Treatments"]["TM"]  =  "சிகிச்சை";
$Prompt["Treatments"]["SL"]  =  "වෙදකම";

$Prompt["Treatment"]["EN"]  =  "Treatment";
$Prompt["Treatment"]["TM"]  =  "சிகிச்சை";
$Prompt["Treatment"]["SL"]  =  "වෙදකම"; 

$Prompt["Alerts"]["EN"]  =  "Alerts";
$Prompt["Alerts"]["TM"]  =  "உஷார்படுத்து";
$Prompt["Alerts"]["SL"]  =  "දැන්වීමේ සංඥාව";

$Prompt["By"]["EN"]  =  "By";
$Prompt["By"]["TM"]  =  "ஆல்";
$Prompt["By"]["SL"]  =  "විසින්";

$Prompt["Active"]["EN"]  =  "Active";
$Prompt["Active"]["TM"]  =  "பாவனை";
$Prompt["Active"]["SL"]  =  "ක්‍රියාකාරී";

$Prompt["Cancel"]["EN"]  =  "Cancel";
$Prompt["Cancel"]["TM"]  =  "விடு";
$Prompt["Cancel"]["SL"]  =  "අවලංගු කරන්න";

$Prompt["Bring this card with you on your next visit"]["EN"]="Bring this card with you on your next visit";
$Prompt["Bring this card with you on your next visit"]["TM"] = "இவ்வட்டையை அடுத்தமுறை வரும்பொழுது கொண்டுவரவும்";
$Prompt["Bring this card with you on your next visit"]["SL"]="මෙම කාඩ්පත ඔබ නැවත පැමිණෙන විට රැගෙන එන්න";

$Prompt["Clear"]["EN"]  =  "Clear";
$Prompt["Clear"]["TM"]  =  "தெளிவாக்கு";
$Prompt["Clear"]["SL"]  =  "අස් කරන්න";

$Prompt["Complaints"]["EN"]  =  "Complaints";
$Prompt["Complaints"]["TM"]  =  "முறைப்பாடு";
$Prompt["Complaints"]["SL"]  =  "පැමිණීල්ල";

$Prompt["Complaint"]["EN"]  =  "Complaint";
$Prompt["Complaint"]["TM"]  =  "முறைப்பாடு";
$Prompt["Complaint"]["SL"]  =  "පැමිණීල්ල";

//lab translations
$Prompt["LabTest"]["EN"] = "LabTest";
$Prompt["LabTest"]["TM"] = "ஆய்வுகூட பரிசோதனை";
$Prompt["LabTest"]["SL"] = "විද්‍යාගාර පරික්ෂණ";

$Prompt["Lab test"]["EN"] = "Lab test";
$Prompt["Lab test"]["TM"] = "ஆய்வுகூட பரிசோதனை";
$Prompt["Lab test"]["SL"] = "විද්‍යාගාර පරික්ෂණ";

$Prompt["Order LabTest"]["EN"] = "Order LabTest";
$Prompt["Order LabTest"]["TM"] = "ஆய்வுகூட பரிசோதனை உருவாக்கு";
$Prompt["Order LabTest"]["SL"] = "විද්‍යාගාර පරික්ෂණ තතනවා";

$Prompt["Lab test group"]["EN"] = "Lab test group";
$Prompt["Lab test group"]["TM"] = "ஆய்வுகூட பரிசோதனை குழு";
$Prompt["Lab test group"]["SL"] = "විද්‍යාගාර පරික්ෂණ කණ්ඩායම්";

$Prompt["Lab test department"]["EN"] = "Lab test department";
$Prompt["Lab test department"]["TM"] = "ஆய்வுகூட பரிசோதனை இலாகா";
$Prompt["Lab test department"]["SL"] = "විද්‍යාගාර පරික්ෂණ අංශය";

//wards translations
$Prompt["Wards"]["EN"] = "Wards";
$Prompt["Wards"]["TM"] = "விடுதிகள்";
$Prompt["Wards"]["SL"] = "වාට්ටුව";

$Prompt["Ward List"]["EN"] = "Ward List";
$Prompt["Ward List"]["TM"] = "விடுதி பட்டியல்";
$Prompt["Ward List"]["SL"] = "වාට්ටු ලැයිස්තුව";

$Prompt["Ward Name"]["EN"] = "Ward Name";
$Prompt["Ward Name"]["TM"] = "விடுதியின் பெயர்";
$Prompt["Ward Name"]["SL"] = "වාට්ටුවේ නාමය";

//printing translations
$Prompt["Print this list"]["EN"] = "Print this list";
$Prompt["Print this list"]["TM"] = "இப்பட்டியலை அச்சிடவும்";
$Prompt["Print this list"]["SL"] = "මුද්‍රණය කරන්න";

//personal information translations
$Prompt["Address"]["EN"]  =  "Address";
$Prompt["Address"]["TM"]  =  "விலாசம்";
$Prompt["Address"]["SL"]  =  "ලිපිනය";

$Prompt["Address 1"]["EN"]  =  "Address 1";
$Prompt["Address 1"]["TM"]  =  "விலாசம் 1";
$Prompt["Address 1"]["SL"]  =  "ලිපිනය 1";

$Prompt["Address 2"]["EN"]  =  "Address 2";
$Prompt["Address 2"]["TM"]  =  "விலாசம் 2";
$Prompt["Address 2"]["SL"]  =  "ලිපිනය 2";

$Prompt["Address: Street"]["EN"]  =  "Address street";
$Prompt["Address: Street"]["TM"]  =  "வீதி";
$Prompt["Address: Street"]["SL"]  =  "මාවත";

$Prompt["Address :Village"]["EN"]  =  "Address village";
$Prompt["Address :Village"]["TM"]  =  "கிராமம்";
$Prompt["Address :Village"]["SL"]  =  "ගම";

$Prompt["Age"]["EN"]  =  "Age";
$Prompt["Age"]["TM"]  =  "வயது";
$Prompt["Age"]["SL"]  =  "වයස";

$Prompt["Civil Status"]["EN"]  =  "Civil status";
$Prompt["Civil Status"]["TM"]  =  "சமூக அந்தஸ்து"; 
$Prompt["Civil Status"]["SL"]  =  "විවාහක අවිවාහක තත්ත්වය";

$Prompt["Contact Telephone"]["EN"]  =  "Contact telephone";
$Prompt["Contact Telephone"]["TM"]  =  "தொலைபேசி";
$Prompt["Contact Telephone"]["SL"]  =  "දුරකථනය";

//data translations
$Prompt["Data tables"]["EN"]  =  "Data tables";
$Prompt["Data tables"]["TM"]  =  "தரவு நிரல்கள்"; 
$Prompt["Data tables"]["SL"]  =  "දත්ත සටහන";

$Prompt["Data accessed"]["EN"]  =  "Data accessed on";
$Prompt["Data accessed"]["TM"]  =  "மாற்றங்கள் செய்த திகதி";
$Prompt["Data accessed"]["SL"]  =  " සංස්කරණය කරන ලද දිනය";

$Prompt["Data created"]["EN"]  =  "Date created";
$Prompt["Data created"]["TM"]  =  "உருவாக்கிய திகதி"; 
$Prompt["Data created"]["SL"]  =  "තනන ලද දිනය";

$Prompt["PID"]["EN"]  =  "PID";
$Prompt["PID"]["TM"]  =  "நோ.இல";
$Prompt["PID"]["SL"]  =  "රෝ.අං";

$Prompt["Days"]["EN"]  =  "Days";
$Prompt["Days"]["TM"]  =  "நாட்கள்";
$Prompt["Days"]["SL"]  =  "දවස්";

$Prompt["Drugs"]["EN"]  =  "Drugs";
$Prompt["Drugs"]["TM"]  =  "மருந்து";
$Prompt["Drugs"]["SL"]  =  "ඖෂධ";

$Prompt["Drug"]["EN"]  =  "Drug";
$Prompt["Drug"]["TM"]  =  "மருந்து";
$Prompt["Drug"]["SL"]  =  "ඖෂධ";

$Prompt["Drug Name"]["EN"]  =  "Drug Name";
$Prompt["Drug Name"]["TM"]  =  "மருந்தின் பெயர்";
$Prompt["Drug Name"]["SL"]  =  "ඖෂධ නම";

$Prompt["Stock"]["EN"]  =  "Stock";
$Prompt["Stock"]["TM"]  =  "இருப்பு";
$Prompt["Stock"]["SL"]  =  "බඩු තොගය";

$Prompt["Edit"]["EN"]  =  "Edit";
$Prompt["Edit"]["TM"]  =  "மாற்றம் செய்";
$Prompt["Edit"]["SL"]  =  "සංස්කරණය කරන්න";

$Prompt["Text"]["EN"]  =  "Text";
$Prompt["Text"]["TM"]  =  "உரை";
$Prompt["Text"]["SL"]  =  "ආදර්ශ පදය";

$Prompt["Entries"]["EN"]  =  "Entries";
$Prompt["Entries"]["TM"]  =  "பதிவுகள்";
$Prompt["Entries"]["SL"]  =  "ඇතුලත් කිරීම්";

$Prompt["First Name"]["EN"]  =  "First Name";
$Prompt["First Name"]["TM"]  =  "முதற்பெயர்";
$Prompt["First Name"]["SL"]  =  "මුල්නම";

$Prompt["Gender"]["EN"]  =  "Gender";
$Prompt["Gender"]["TM"]  =  "பால்";
$Prompt["Gender"]["SL"]  =  "ස්ත්‍රී/පුරුෂ භාවය";

$Prompt["Male"]["EN"]  =  "Male";
$Prompt["Male"]["TM"]  =  "ஆண்";
$Prompt["Male"]["SL"]  =  "පුරුෂ";

$Prompt["Female"]["EN"]  =  "Female";
$Prompt["Female"]["TM"]  =  "பெண்";
$Prompt["Female"]["SL"]  =  "ස්ත්‍රී";

$Prompt["Give an Admission"]["EN"]  =  "Give an Admission";
$Prompt["Give an Admission"]["TM"]  =  "அனுமதி வழங்கு";
$Prompt["Give an Admission"]["SL"]  =  "ඇතුළත් කිරීමට අවසර දෙන්න";

$Prompt["Give an appointment"]["EN"]  =  "Give an appointment";
$Prompt["Give an appointment"]["TM"]  =  "நியமனம் வழங்கல்";
$Prompt["Give an appointment"]["SL"]  =  "හමුවීමට දිනයක් ලබා දෙන්න";

$Prompt["Give an OPD visit"]["EN"]  =  "Give an OPD visit";
$Prompt["Give an OPD visit"]["TM"]  =  "வெளிநோயாளர் பதிவு";
$Prompt["Give an OPD visit"]["SL"]  =  "බාහිර රෝගී අංශයට පැමිණීමට අවසර දෙන්න";

$Prompt["Give a clinic visit"]["EN"]  =  "Give clinic visit";
$Prompt["Give a clinic visit"]["TM"]  =  "பண்டுமனை பதிவு";
$Prompt["Give a clinic visit"]["SL"]  =  "සායනයට පැමිණීමට අවසර දෙන්න";

$Prompt["Home"]["EN"]  =  "Home";
$Prompt["Home"]["TM"]  =  "முதற்பக்கம்";
$Prompt["Home"]["SL"]  =  "මුල්පිටුව";

$Prompt["Home page"]["EN"]  =  "Home page";
$Prompt["Home page"]["TM"]  =  "முதற்பக்கம்";
$Prompt["Home page"]["SL"]  =  "මුල්පිටුව";

$Prompt["Home Page"]["EN"]  =  "Home page";
$Prompt["Home Page"]["TM"]  =  "முதற்பக்கம்";
$Prompt["Home Page"]["SL"]  =  "මුල්පිටුව";

$Prompt["Hospital"]["EN"]  =  "Hospital";
$Prompt["Hospital"]["TM"]  =  "வைத்தியசாலை";
$Prompt["Hospital"]["SL"]  =  "රෝහල";

$Prompt["Hospital Settings"]["EN"]  =  "Hospital Settings";
$Prompt["Hospital Settings"]["TM"]  =  "வைத்தியசாலை ஒழுங்குகள்";
$Prompt["Hospital Settings"]["SL"]  =  "රෝහලේ සිටුවම්";

$Prompt["Licensed to"]["EN"]  =  "Licensed to";
$Prompt["Licensed to"]["TM"]  =  "அனுமதிப்பத்திரம்";
$Prompt["Licensed to"]["SL"]  =  "බලපත්‍රය";

$Prompt["Log Out"]["EN"]  =  "Log Out";
$Prompt["Log Out"]["TM"]  =  "வெளியேறு";
$Prompt["Log Out"]["SL"]  =  "වරන්න";

$Prompt["Login"]["EN"]  =  "Login";
$Prompt["Login"]["TM"]  =  "உட்புகு";
$Prompt["Login"]["SL"]  =  "පුරන්න";

$Prompt["Menu Bar"]["EN"]  =  "Menu Bar";
$Prompt["Menu Bar"]["TM"]  =  "முதன்மை பட்டி";
$Prompt["Menu Bar"]["SL"]  =  "මෙනු තීරුව";

$Prompt["Months"]["EN"]  =  "Months";
$Prompt["Months"]["TM"]  =  "மாதங்கள்";
$Prompt["Months"]["SL"]  =  "මාස";

$Prompt["Full Name"]["EN"]  =  "Full Name";
$Prompt["Full Name"]["TM"]  =  "முழுப்பெயர்";
$Prompt["Full Name"]["SL"]  =  "සම්පුර්ණ නම";

$Prompt["New Patient"]["EN"]  =  "New patient";
$Prompt["New Patient"]["TM"]  =  "புதிய நோயாளி";
$Prompt["New Patient"]["SL"]  =  "අළුත් රෝගියෙකි";

$Prompt["Patient"]["EN"]  =  "Patient";
$Prompt["Patient"]["TM"]  =  "நோயாளி";
$Prompt["Patient"]["SL"]  =  "රෝගියෙකි";

$Prompt["Patient Admission Information"]["EN"]  =  "Patient Admission Information";
$Prompt["Patient Admission Information"]["TM"]  =  "நோயாளியின் அனுமதி பற்றிய விபரம்";
$Prompt["Patient Admission Information"]["SL"]  =  "රෝගියාගේ අනුමත පිළිබඳ තොරතුරු";

$Prompt["NIC"]["EN"]  =  "NIC";
$Prompt["NIC"]["TM"]  =  "தே.அ.அ";
$Prompt["NIC"]["SL"]  =  "ජා.හැ.ප";

$Prompt["Other Name"]["EN"]  =  "* Other Name";
$Prompt["Other Name"]["TM"]  =  "வேறு பெயர்";
$Prompt["Other Name"]["SL"]  =  "වෙනත් නම්";

$Prompt["Password"]["EN"]  =  "Password";
$Prompt["Password"]["TM"]  =  "கடவுச்சொல்";
$Prompt["Password"]["SL"]  =  "මුර පදය";

$Prompt["Current password"]["EN"]  =  "Current password";
$Prompt["Current password"]["TM"]  =  "தற்போதைய கடவுச்சொல்";
$Prompt["Current password"]["SL"]  =  "භාවිතයේ පවතින මුර පදය";

$Prompt["Patient overview"]["EN"]  =  "Patient overview";
$Prompt["Patient overview"]["TM"]  =  "நோயாளர் மேற்பார்வை";
$Prompt["Patient overview"]["SL"]  =  "රෝගියාගේ දළ විශ්ලේෂණය";

$Prompt["Patient search"]["EN"]  =  "Patient search";
$Prompt["Patient search"]["TM"]  =  "நோயாளர் தேடல்";
$Prompt["Patient search"]["SL"]  =  "රෝගියාව සොයන්න";

$Prompt["Post"]["EN"]  =  "Post"; 
$Prompt["Post"]["TM"]  =  "உத்தியோகம்";
$Prompt["Post"]["SL"]  =  "නියමිත ස්ථානය";

$Prompt["Preferences"]["EN"]  =  "Preference";
$Prompt["Preferences"]["TM"]  =  "விருப்பக்குறிப்பு";
$Prompt["Preferences"]["SL"]  =  "මනාපය";

$Prompt["Print patient card"]["EN"]  =  "Print patient cards";
$Prompt["Print patient card"]["TM"]  =  "நோயாளர் அட்டை";
$Prompt["Print patient card"]["SL"]  =  "රෝගියාගේ කාඩ් පත";

$Prompt["Print patient history"]["EN"]  =  "Print patient history";
$Prompt["Print patient history"]["TM"]  =  "நோயாளர் வரலாறு";
$Prompt["Print patient history"]["SL"]  =  "රෝගියාගේ වෛද්‍ය ඉතිහාසය";

$Prompt["Patient history"]["EN"]  =  "Patient history";
$Prompt["Patient history"]["TM"]  =  "நோயாளர் வரலாறு";
$Prompt["Patient history"]["SL"]  =  "රෝගියාගේ වෛද්‍ය ඉතිහාසය";

$Prompt["Print patient slip"]["EN"]  =  "Print patient slip";
$Prompt["Print patient slip"]["TM"]  =  "நோயாளர் சீட்டு";
$Prompt["Print patient slip"]["SL"]  =  "රෝගියාගේ තුණ්ඩුව";

$Prompt["Prints"]["EN"]  =  "Prints";
$Prompt["Prints"]["TM"]  =  "அச்சுபிரதி";
$Prompt["Prints"]["SL"]  =  "මුද්‍රණ";

$Prompt["Recent patients"]["EN"]  =  "Recent patients";
$Prompt["Recent patients"]["TM"]  =  "அண்மையில் பார்வையிட்ட நோயாளிகள்";
$Prompt["Recent patients"]["SL"]  =  "අලුතෙන් බලනු ලෙඩ්ඩු";

$Prompt["Patients"]["EN"]  =  "Patients";
$Prompt["Patients"]["TM"]  =  "நோயாளிகள்";
$Prompt["Patients"]["SL"]  =  "ලෙඩ්ඩු";

$Prompt["Registration No"]["EN"]  =  "Registration No";
$Prompt["Registration No"]["TM"]  =  "பதிவு இல";
$Prompt["Registration No"]["SL"]  =  "ලියාපදිංචි අංකය";

$Prompt["Remarks"]["EN"]  =  "Remarks";
$Prompt["Remarks"]["TM"]  =  "மேலதிக தகவல்";
$Prompt["Remarks"]["SL"]  =  "සටහන්";

$Prompt["Save"]["EN"]  =  "Save";
$Prompt["Save"]["TM"]  =  "சேமி";
$Prompt["Save"]["SL"]  =  "සුරකින්න";

$Prompt["Search"]["EN"]  =  "Search";
$Prompt["Search"]["TM"]  =  "தேடு";
$Prompt["Search"]["SL"]  =  "සොයන්න";

$Prompt["Show"]["EN"]  =  "Show";
$Prompt["Show"]["TM"]  =  "காட்டு";
$Prompt["Show"]["SL"]  =  "පෙන්වන්න";

$Prompt["Title"]["EN"]  =  "Title";
$Prompt["Title"]["TM"]  =  "வணக்கமுறை";
$Prompt["Title"]["SL"]  =  "ආචාරය";

$Prompt["Years"]["EN"]  =  "Years";
$Prompt["Years"]["TM"]  =  "வருடங்கள்";
$Prompt["Years"]["SL"]  =  "අවුරුදු";

$Prompt["User"]["EN"]  =  "User";
$Prompt["User"]["TM"]  =  "பயனர்";
$Prompt["User"]["SL"]  =  "පරිශීලක";

$Prompt["User Group"]["EN"]  =  "User Group";
$Prompt["User Group"]["TM"]  =  "பயனர் குழு";
$Prompt["User Group"]["SL"]  =  "පරිශීලක කණ්ඩායම";

$Prompt["User group"]["EN"]  =  "User group";
$Prompt["User group"]["TM"]  =  "பயனர் குழு";
$Prompt["User group"]["SL"]  =  "පරිශීලක කණ්ඩායම";

$Prompt["UserGroup"]["EN"]  =  "UserGroup";
$Prompt["UserGroup"]["TM"]  =  "பயனர் குழு";
$Prompt["UserGroup"]["SL"]  =  "පරිශීලක කණ්ඩායම";

$Prompt["User name"]["EN"]  =  "User name";
$Prompt["User name"]["TM"]  =  "பயனாளர் பெயர்";
$Prompt["User name"]["SL"]  =  "පරිශීලක නාමය";

$Prompt["Group Name"]["EN"]  =  "Group Name";
$Prompt["Group Name"]["TM"]  =  "குழு பெயர்";
$Prompt["Group Name"]["SL"]  =  "කණ්ඩායම නාමය";

$Prompt["Village"]["EN"]  =  "Village";
$Prompt["Village"]["TM"]  =  "கிராமம்";
$Prompt["Village"]["SL"]  =  "ගම";

$Prompt["Villages"]["EN"]  =  "Villages";
$Prompt["Villages"]["TM"]  =  "கிராமங்கள்";
$Prompt["Villages"]["SL"]  =  "ගම්මාන";

$Prompt["Doctor"]["EN"]  =  "Doctor";
$Prompt["Doctor"]["TM"]  =  "வைத்தியர்";
$Prompt["Doctor"]["SL"]  =  "වෛද්‍යවරයා";

$Prompt["ID"]["EN"] = "ID";
$Prompt["ID"]["TM"] = "இல";
$Prompt["ID"]["SL"] = "අංකය";

$Prompt["Date and time of visit"]["EN"]  =  "Date and time of visit";
$Prompt["Date and time of visit"]["TM"]  =  "வருகைக்கான நேரமும் திகதியும்";
$Prompt["Date and time of visit"]["SL"]  =  "පැමිණීමේ වේලාව සහ දිනය";

$Prompt["Date and time of Discharge"]["EN"]  =  "Date and time of Discharge";
$Prompt["Date and time of Discharge"]["TM"]  =  "விலக்களித்தல் நேரமும் திகதியும்";
$Prompt["Date and time of Discharge"]["SL"]  =  "අස් කිරීමේ වේලාව සහ දිනය";

$Prompt["Date and Time of visit"]["EN"]  =  "Date and Time of visit";
$Prompt["Date and Time of visit"]["TM"]  =  "வருகைக்கான நேரமும் திகதியும்";
$Prompt["Date and Time of visit"]["SL"]  =  "පැමිණීමේ වේලාව සහ දිනය";

$Prompt["Onset Date"]["EN"]  =  "Onset Date";
$Prompt["Onset Date"]["TM"]  =  "ஆரம்பித்த திகதி";
$Prompt["Onset Date"]["SL"]  =  "ආරම්භ කල දිනය";

$Prompt["Dosage"]["EN"]  =  "Dosage";
$Prompt["Dosage"]["TM"]  =  "மருந்தளவு";
$Prompt["Dosage"]["SL"]  =  "බේත් ප්‍රමාණය";

$Prompt["Period"]["EN"]  =  "Period";
$Prompt["Period"]["TM"]  =  "காலம்";
$Prompt["Period"]["SL"]  =  "කාලය";

$Prompt["Complaints / Injury"]["EN"] = "Complaints / Injury";
$Prompt["Complaints / Injury"]["TM"] = "முறைப்பாடுகள் அல்லது காயங்கள்";
$Prompt["Complaints / Injury"]["SL"] = "පැමිණීල්ල හෝ තුවාලය";

$Prompt["Complaints / Injuries"]["EN"] = "Complaints / Injuries";
$Prompt["Complaints / Injuries"]["TM"] = "முறைப்பாடுகள் அல்லது காயங்கள்";
$Prompt["Complaints / Injuries"]["SL"] = "පැමිණීල්ල හෝ තුවාලය";

$Prompt["Injuries"]["EN"] = "Injuries";
$Prompt["Injuries"]["TM"] = "காயங்கள்";
$Prompt["Injuries"]["SL"] = "තුවාලය";

$Prompt["Prescribed on"]["EN"]  =  "Prescribed on";
$Prompt["Prescribed on"]["TM"]  =  "எழுதிய திகதி";
$Prompt["Prescribed on"]["SL"]  =  "නිර්දේශ කල දිනය";

$Prompt["Prescribed On"]["EN"]  =  "Prescribed On";
$Prompt["Prescribed On"]["TM"]  =  "எழுதிய திகதி";
$Prompt["Prescribed On"]["SL"]  =  "නිර්දේශ කල දිනය";

$Prompt["Prescribe by"]["EN"]  =  "Prescribe by";
$Prompt["Prescribe by"]["TM"]  =  "எழுதியவர்";
$Prompt["Prescribe by"]["SL"]  =  "නිර්දේශ කරන්නාගේ නම";

$Prompt["Prescribe By"]["EN"]  =  "Prescribe By";
$Prompt["Prescribe By"]["TM"]  =  "எழுதியவர்";
$Prompt["Prescribe By"]["SL"]  =  "නිර්දේශ කරන්නාගේ නම";

$Prompt["Prescribed By"]["EN"]  =  "Prescribed By";
$Prompt["Prescribed By"]["TM"]  =  "எழுதியவர்";
$Prompt["Prescribed By"]["SL"]  =  "නිර්දේශ කරන්නාගේ නම";

$Prompt["Prescribe drugs"]["EN"]  =  "Prescribe drugs";
$Prompt["Prescribe drugs"]["TM"]  =  "எழுதப்பட்ட மருந்துகள்";
$Prompt["Prescribe drugs"]["SL"]  =  "නිර්දේශ කරන ලද ඖෂධ";

$Prompt["Prescribe Date"]["EN"]  =  "Prescribe Date";
$Prompt["Prescribe Date"]["TM"]  =  "எழுதப்பட்ட திகதி";
$Prompt["Prescribe Date"]["SL"]  =  "නිර්දේශ කිරීමේ දිනය";

$Prompt["Prescription"]["EN"]  =  "Prescription";
$Prompt["Prescription"]["TM"]  =  "மருந்துச்சீட்டு";
$Prompt["Prescription"]["SL"]  =  "බෙහෙත් වට්ටෝරුව";

$Prompt["Prescription ID"]["EN"]  =  "Prescription ID";
$Prompt["Prescription ID"]["TM"]  =  "மருந்துச்சீட்டு இல";
$Prompt["Prescription ID"]["SL"]  =  "බෙහෙත් වට්ටෝරු අංකය";

$Prompt["OPD Prescription"]["EN"]  =  "OPD Prescription";
$Prompt["OPD Prescription"]["TM"]  =  "வெளிநோயாளர் பிரிவு மருந்துச்சீட்டு";
$Prompt["OPD Prescription"]["SL"]  =  "බාහිර රෝගී අංශයේ බෙහෙත් වට්ටෝරුව";

$Prompt["Order Date"]["EN"]  =  "Order Date";
$Prompt["Order Date"]["TM"]  =  "கட்டளை திகதி";
$Prompt["Order Date"]["SL"]  =  "නියෝග දිනය";

$Prompt["OPD Lab Order"]["EN"]  =  "OPD Lab Order";
$Prompt["OPD Lab Order"]["TM"]  =  "வெளிநோயாளர் பிரிவு ஆய்வுக்கூட கட்டளை";
$Prompt["OPD Lab Order"]["SL"]  =  "බාහිර රෝගී අංශයේ පරීක්ෂණාගාරයේ නියෝගය";

$Prompt["Edit OPD Lab Order"]["EN"]  =  "Edit OPD Lab Order";
$Prompt["Edit OPD Lab Order"]["TM"]  =  "வெளிநோயாளர் பிரிவு ஆய்வுக்கூட கட்டளையில் மாற்றம் செய்தல்";
$Prompt["Edit OPD Lab Order"]["SL"]  =  "බාහිර රෝගී අංශයේ පරීක්ෂණාගාරයේ නියෝගය සංස්කරණය කරන්න";

$Prompt["Lab Order"]["EN"]  =  "Lab Order";
$Prompt["Lab Order"]["TM"]  =  "ஆய்வுக்கூட கட்டளை";
$Prompt["Lab Order"]["SL"]  =  "පරීක්ෂණාගාරයේ නියෝගය";

$Prompt["Order By"]["EN"]  =  "Order By";
$Prompt["Order By"]["TM"]  =  "கட்டளையிடுபவர்";
$Prompt["Order By"]["SL"]  =  "නියෝග කරන්නාගේ නම";

$Prompt["Dept"]["EN"]  =  "Dept";
$Prompt["Dept"]["TM"]  =  "இலாகா";
$Prompt["Dept"]["SL"]  =  "අංශය";

$Prompt["Reports"]["EN"]  =  "Reports";
$Prompt["Reports"]["TM"]  =  "அறிக்கை";
$Prompt["Reports"]["SL"]  =  "වාර්තාව";

$Prompt["First"]["EN"]  =  "First";
$Prompt["First"]["TM"]  =  "முதல்";
$Prompt["First"]["SL"]  =  "පළමු";

$Prompt["Previous"]["EN"]  =  "Previous";
$Prompt["Previous"]["TM"]  =  "முன்னைய";
$Prompt["Previous"]["SL"]  =  "පෙර";

$Prompt["Next"]["EN"]  =  "Next";
$Prompt["Next"]["TM"]  =  "அடுத்த";
$Prompt["Next"]["SL"]  =  "ඊළඟ";

$Prompt["Last"]["EN"]  =  "Last";
$Prompt["Last"]["TM"]  =  "கடைசி";
$Prompt["Last"]["SL"]  =  "අවසාන";

$Prompt["Daily drugs dispensed"]["EN"]  =  "Daily drugs dispensed";
$Prompt["Daily drugs dispensed"]["TM"]  =  "தினசரி வழங்கப்பட்ட மருந்து";
$Prompt["Daily drugs dispensed"]["SL"]  =  "දිනපතා නියම කරන ලද ඖෂධ";

$Prompt["Dispense Form"]["EN"]  =  "Dispense Form";
$Prompt["Dispense Form"]["TM"]  =  "வழங்கப்பட்ட மருந்துக்கான படிவம்";
$Prompt["Dispense Form"]["SL"]  =  "නියම කරන ලද ඖෂධ පිළිවෙළ";

$Prompt["Order ID"]["EN"]  =  "Order ID";
$Prompt["Order ID"]["TM"]  =  "கட்டளை இல";
$Prompt["Order ID"]["SL"]  =  "නියෝග අංකය";

$Prompt["Ordering On"]["EN"]  =  "Ordering On";
$Prompt["Ordering On"]["TM"]  =  "கட்டளை திகதி";
$Prompt["Ordering On"]["SL"]  =  "නියෝග දිනය";

$Prompt["Ordering By"]["EN"]  =  "Ordering By";
$Prompt["Ordering By"]["TM"]  =  "கட்டளையிடுபவர்";
$Prompt["Ordering By"]["SL"]  =  "නියෝග කරන්නාගේ නම";

$Prompt["Pharmacy"]["EN"] = "Pharmacy";
$Prompt["Pharmacy"]["TM"] = "மருந்தகம்";
$Prompt["Pharmacy"]["SL"] = "බෙහෙත් ශාලාව";

$Prompt["Laboratory"]["EN"] = "Laboratory";
$Prompt["Laboratory"]["TM"] = "ஆய்வுகூடம்";
$Prompt["Laboratory"]["SL"] = "විද්‍යාගාරය";

$Prompt["Commands"]["EN"] = "Commands";
$Prompt["Commands"]["TM"] = "கட்டளை";
$Prompt["Commands"]["SL"] = "අණදීම";

$Prompt["Create a visit"]["EN"] = "Create a visit";
$Prompt["Create a visit"]["TM"] = "வருகையை உருவாக்கு";
$Prompt["Create a visit"]["SL"] = "පැමීණීම නිර්මාණය කරන්න";

$Prompt["Add allergy"]["EN"] = "Add allergy";
$Prompt["Add allergy"]["TM"] = "அலேர்ஜியை சேர்";
$Prompt["Add allergy"]["SL"] = "අලෙර්ජ් එකතු කරන්න";

$Prompt["Your recent patients"]["EN"] = "Your recent patients";
$Prompt["Your recent patients"]["TM"] = "நீங்கள் அண்மையில் பார்வையிட்ட நோயாளிகள்";
$Prompt["Your recent patients"]["SL"] = "අලුතෙන් බලනු ලෙඩ්ඩු";

$Prompt["Full Registered Name"]["EN"] = "Full Registered Name";
$Prompt["Full Registered Name"]["TM"] = "பதிவு செய்யப்பட்ட முழுப்பெயர்";
$Prompt["Full Registered Name"]["SL"] = "ලියාපදිංචි කරණලද සම්පූර්ණ නම";

$Prompt["Allergies"]["EN"] = "Allergies";
$Prompt["Allergies"]["TM"] = "அலர்ஜி";
$Prompt["Allergies"]["SL"] = "අලෙර්ජික්";

$Prompt["OK"]["EN"] = "OK";
$Prompt["OK"]["TM"] = "அனுமதித்தல்";
$Prompt["OK"]["SL"] = "අනුමත කිරීම";

$Prompt["Ward"]["EN"] = "Ward";
$Prompt["Ward"]["TM"] = "விடுதி";
$Prompt["Ward"]["SL"] = "වාට්ටුව";

$Prompt["Ward No."]["EN"] = "Ward No.";
$Prompt["Ward No."]["TM"] = "விடுதி இல";
$Prompt["Ward No."]["SL"] = "වාට්ටු අංකය";

$Prompt["Beds"]["EN"] = "Beds";
$Prompt["Beds"]["TM"] = "கட்டில்கள்";
$Prompt["Beds"]["SL"] = "සයනයන්";

$Prompt["Previous visits"]["EN"] = "Previous visits";
$Prompt["Previous visits"]["TM"] = "முன்னைய வருகை";
$Prompt["Previous visits"]["SL"] = "පසුගිය පැමිණීම";

$Prompt["Visits"]["EN"] = "Visits";
$Prompt["Visits"]["TM"] = "வருகை";
$Prompt["Visits"]["SL"] = "පැමිණීම";

$Prompt["Lab orders"]["EN"] = "Lab orders";
$Prompt["Lab orders"]["TM"] = "ஆய்வுகூட கட்டளை";
$Prompt["Lab orders"]["SL"] = "විද්‍යාගාරය නියෝග";

$Prompt["Summary"]["EN"] = "Summary";
$Prompt["Summary"]["TM"] = "பொழிப்பு";
$Prompt["Summary"]["SL"] = "සාරාංශය";

$Prompt["Visit type"]["EN"] = "Visit type";
$Prompt["Visit type"]["TM"] = "வருகை";
$Prompt["Visit type"]["SL"] = "පැමිණීම";

$Prompt["Name"]["EN"] = "Name";
$Prompt["Name"]["TM"] = "பெயர்";
$Prompt["Name"]["SL"] = "නම";

//system related translations
$Prompt["System Tables"]["EN"] = "System User";
$Prompt["System Tables"]["TM"] = "செயலி நிரல்கள்";
$Prompt["System Tables"]["SL"] =  "ක්‍රියාවලි සටහන්";

$Prompt["System User"]["EN"] = "System User";
$Prompt["System User"]["TM"] = "செயலி பயனாளர்";
$Prompt["System User"]["SL"] = "ක්‍රියාවලි පරිශීලක";

$Prompt["System user edit/new"]["EN"] = "System user edit/new";
$Prompt["System user edit/new"]["TM"] = "புதிய செயலி பயனாளர்/மாற்றம் செய்";
$Prompt["System user edit/new"]["SL"] = "අළුත් ක්‍රියාවලි පරිශීලක/සංස්කරණය කරන්න";

$Prompt["Bed Head No"]["EN"] = "Bed Head No";
$Prompt["Bed Head No"]["TM"] = "படுக்கை இல";
$Prompt["Bed Head No"]["SL"] = "සයනයේ අංකය";

//date translations
$Prompt["Date/Age/Year"]["EN"] = "Date/Age/Year";
$Prompt["Date/Age/Year"]["TM"] = "திகதி/வயது/வருடம்";
$Prompt["Date/Age/Year"]["SL"] = " දිනය/වයස/අවුරුදු";

$Prompt["Date and time of admission"]["EN"]  =  "Date and time of admission";
$Prompt["Date and time of admission"]["TM"]  =  "அனுமதிக்கான நேரமும் திகதியும்";
$Prompt["Date and time of admission"]["SL"]  =  "අනුමතිය වේලාව සහ දිනය";

$Prompt["Date and time of Admission"]["EN"]  =  "Date and time of Admission";
$Prompt["Date and time of Admission"]["TM"]  =  "அனுமதிக்கான நேரமும் திகதியும்";
$Prompt["Date and time of Admission"]["SL"]  =  "අනුමතිය වේලාව සහ දිනය";

$Prompt["Date of birth"]["EN"]  =  "Date of birth";
$Prompt["Date of birth"]["TM"]  =  "பிறந்த திகதி";
$Prompt["Date of birth"]["SL"]  =  "උපන් දිනය";

$Prompt["Date"]["EN"]  =  "Date";
$Prompt["Date"]["TM"]  =  "திகதி";
$Prompt["Date"]["SL"]  =  "දිනය";

$Prompt["DOB"]["EN"]  =  "DOB";
$Prompt["DOB"]["TM"]  =  "பி.திகதி";
$Prompt["DOB"]["SL"]  =  "උ. දිනය";

//SNOMED translations
$Prompt["SNOMED Procedure"]["EN"] = "SNOMED Procedure";
$Prompt["SNOMED Procedure"]["TM"] = "SNOMED படிமுறைகள்";
$Prompt["SNOMED Procedure"]["SL"] = "SNOMED පිළිවෙළ";

$Prompt["SNOMED Procedures"]["EN"] = "SNOMED Procedures";
$Prompt["SNOMED Procedures"]["TM"] = "SNOMED படிமுறைகள்";
$Prompt["SNOMED Procedures"]["SL"] = "SNOMED පිළිවෙළ";

$Prompt["SNOMED Findings"]["EN"] = "SNOMED Findings";
$Prompt["SNOMED Findings"]["TM"] = "SNOMED தேடுதல்கள்";
$Prompt["SNOMED Findings"]["SL"] = "SNOMED සොයාගැනිම";

$Prompt["SNOMED Finding"]["EN"] = "SNOMED Findings";
$Prompt["SNOMED Finding"]["TM"] = "SNOMED தேடுதல்கள்";
$Prompt["SNOMED Finding"]["SL"] = "SNOMED සොයාගැනිම";

$Prompt["SNOMED Disorders"]["EN"] = "SNOMED Disorders";
$Prompt["SNOMED Disorders"]["TM"] = "SNOMED தேடுதல்கள்";
$Prompt["SNOMED Disorders"]["SL"] = "SNOMED සොයාගැනිම";

$Prompt["SNOMED Events"]["EN"] = "SNOMED Events";
$Prompt["SNOMED Events"]["TM"] = "SNOMED நிகழ்வுகள்";
$Prompt["SNOMED Events"]["SL"] = "SNOMED සිද්ධිය";

//add /new /edit translations
$Prompt["New OPD Visit"]["EN"] = "New OPD Visit";
$Prompt["New OPD Visit"]["TM"] = "புதிய வெளிநோயாளர் வருகை";
$Prompt["New OPD Visit"]["SL"] = "බාහිර රෝගී අංශයට අළුත් පැමිණීම";

$Prompt["New admission"]["EN"] = "New admission";
$Prompt["New admission"]["TM"] = "புதிய அனுமதி";
$Prompt["New admission"]["SL"] = "අළුත් අනුමතිය";

$Prompt["Admissions"]["EN"] = "Admissions";
$Prompt["Admissions"]["TM"] = "அனுமதிகள்";
$Prompt["Admissions"]["SL"] = "අනුමතිය";

$Prompt["New patient registration"]["EN"] = "New patient registration";
$Prompt["New patient registration"]["TM"] = "புதிய நோயாளர் பதிவு";
$Prompt["New patient registration"]["SL"] = "අළුත් රෝගියාගේ ලියාපදිංචිය";

$Prompt["Add history"]["EN"] = "Add history";
$Prompt["Add history"]["TM"] = "வரலாறை சேர்";
$Prompt["Add history"]["SL"] = "ඉතිහාසය එකතු කරන්න";

$Prompt["Past history"]["EN"] = "Past history";
$Prompt["Past history"]["TM"] = "கடந்தகால வரலாறு";
$Prompt["Past history"]["SL"] = "අතීත ඉතිහාසය";

$Prompt["Add new User / Staff"]["EN"]  =  "Add new User / Staff";
$Prompt["Add new User / Staff"]["TM"]  =  "புதிய பயனாளர்";
$Prompt["Add new User / Staff"]["SL"]  =  "අළුත් පරිශීලකයින්";

$Prompt["Add new complaint"]["EN"]  =  "Add new complaint";
$Prompt["Add new complaint"]["TM"]  =  "புதிய முறைப்பாடு";
$Prompt["Add new complaint"]["SL"]  =  "අළුත් පැමිණීල්ල";

$Prompt["Add new treatment"]["EN"]  =  "Add new treatment";
$Prompt["Add new treatment"]["TM"]  =  "புதிய சிகிச்சை";
$Prompt["Add new treatment"]["SL"]  =  "අළුත් වෙදකම";

$Prompt["Add new drug"]["EN"]  =  "Add new drug";
$Prompt["Add new drug"]["TM"]  =  "புதிய மருந்துகள்";
$Prompt["Add new drug"]["SL"]  =  "අළුත් ඖෂධ";

$Prompt["Add new LabTest"]["EN"] = "Add new LabTest";
$Prompt["Add new LabTest"]["TM"] = "புதிய ஆய்வுகூட பரிசோதனை";
$Prompt["Add new LabTest"]["SL"] = "අළුත් විද්‍යාගාර පරික්ෂණ";

$Prompt["Add new Lab group"]["EN"] = "Add new Lab group";
$Prompt["Add new Lab group"]["TM"] = "புதிய ஆய்வுகூட குழு";
$Prompt["Add new Lab group"]["SL"] = "අළුත් විද්‍යාගාර කණ්ඩායම්";

$Prompt["Add new Lab department"]["EN"] = "Add new Lab department";
$Prompt["Add new Lab department"]["TM"] = "புதிய ஆய்வுகூட இலாகா";
$Prompt["Add new Lab department"]["SL"] = "අළුත් විද්‍යාගාර අංශය";

$Prompt["Add new User / Wards"]["EN"] = "Add new User / Wards";
$Prompt["Add new User / Wards"]["TM"] = "புதிய நோயாளர் கூடம்";
$Prompt["Add new User / Wards"]["SL"] = "අළුත් වාට්ටුව";

$Prompt["Add further information about the patient"]["EN"]  =  "Add further information about the patient";
$Prompt["Add further information about the patient"]["TM"]  =  "நோயாளியின் மேலதிக தகவல்களை சேர்த்தல்";
$Prompt["Add further information about the patient"]["SL"]  =  "රෝගියා පිළිබඳ අතිරේක විස්තර සදහන් කරන්න";

$Prompt["Add/Edit Canned text"]["EN"] = "Add/Edit Canned text";
$Prompt["Add/Edit Canned text"]["TM"] = "சொற்சுருக்கத்தை சேர்/மாற்றம் செய்";
$Prompt["Add/Edit Canned text"]["SL"] = "කෙටි සටහන එකතු කරන්න/සංස්කරණය කරන්න";

$Prompt["Add/Edit Permission"]["EN"]  =  "Add/Edit Permission";
$Prompt["Add/Edit Permission"]["TM"]  =  "அனுமதித்தல்/மாற்றம் செய்";
$Prompt["Add/Edit Permission"]["SL"]  =  "අනුමතිය එකතු කරන්න/සංස්කරණය කරන්න";

$Prompt["Add / Edit Admission Notes"]["EN"]  =  "Add / Edit Admission Notes";
$Prompt["Add / Edit Admission Notes"]["TM"]  =  "அனுமதி குறிப்பை சேர்/மாற்றம் செய்";
$Prompt["Add / Edit Admission Notes"]["SL"]  =  "අනුමති විස්තරය එකතු කරන්න/සංස්කරණය කරන්න";

$Prompt["Add/Edit Group"]["EN"]  =  "Add/Edit Group";
$Prompt["Add/Edit Group"]["TM"]  =  "குழுவை சேர்/மாற்றம் செய்";
$Prompt["Add/Edit Group"]["SL"]  =  "කණ්ඩායම එකතු කරන්න/සංස්කරණය කරන්න";

$Prompt["Add/Edit Users"]["EN"]  =  "Add/Edit Users";
$Prompt["Add/Edit Users"]["TM"]  =  "பயனாளரை சேர்/மாற்றம் செய்";
$Prompt["Add/Edit Users"]["SL"]  =  "පරිශීලකයින් එකතු කරන්න/සංස්කරණය කරන්න";

$Prompt["Add / Edit Allergy"]["EN"] = "Add / Edit Allergy";
$Prompt["Add / Edit Allergy"]["TM"] = "அலேர்ஜியை சேர் / மாற்றம் செய்";
$Prompt["Add / Edit Allergy"]["SL"] = "අලෙර්ජ් එකතු කරන්න / සංස්කරණය කරන්න";

$Prompt["Add / Edit Patient History"]["EN"] = "Add / Edit Patient History";
$Prompt["Add / Edit Patient History"]["TM"] = "நோயாளியின் வரலாறை சேர் / மாற்றம் செய்";
$Prompt["Add / Edit Patient History"]["SL"] = "රෝගියාගේ ඉතිහාසය එකතු කරන්න / සංස්කරණය කරන්න";

$Prompt["Add / Edit Patient Examination"]["EN"] = "Add / Edit Patient Examination";
$Prompt["Add / Edit Patient Examination"]["TM"] = "நோயாளியின் பரிசோதனையை சேர் / மாற்றம் செய்";
$Prompt["Add / Edit Patient Examination"]["SL"] = "රෝගියාගේ පරීක්ෂණය එකතු කරන්න / සංස්කරණය කරන්න";

$Prompt["Add/Edit Visit Type"]["EN"] = "Add/Edit Visit Type";
$Prompt["Add/Edit Visit Type"]["TM"] = "வருகையை சேர்/மாற்றம் செய்";
$Prompt["Add/Edit Visit Type"]["SL"] = "පැමිණීම එකතු කරන්න / සංස්කරණය කරන්න";

$Prompt["Edit patient registration"]["EN"] = "Edit patient registration";
$Prompt["Edit patient registration"]["TM"] = "நோயாளர் பதிவுகளில் மாற்றம் செய்தல்";
$Prompt["Edit patient registration"]["SL"] = "රෝගියාගේ ලියාපදිංචිය සංස්කරණය";

$Prompt["Allergy"]["EN"] = "Allergy";
$Prompt["Allergy"]["TM"] = "அலர்ஜி";
$Prompt["Allergy"]["SL"] = "අලෙර්ජික්";

$Prompt["Status"]["EN"] = "Status";
$Prompt["Status"]["TM"] = "நிலைமை";
$Prompt["Status"]["SL"] = "තත්වය";
?>