<?php
/*
--------------------------------------------------------------------------------
HHIMS - Hospital Health Information Management System
Copyright (c) 2011 Information and Communication Technology Agency of Sri Lanka
<http: www.hhims.org/>
----------------------------------------------------------------------------------
This program is free software: you can redistribute it and/or modify it under the
terms of the GNU Affero General Public License as published by the Free Software 
Foundation, either version 3 of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,but WITHOUT ANY 
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR 
A PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License along 
with this program. If not, see <http://www.gnu.org/licenses/> or write to:
Free Software  HHIMS
C/- Lunar Technologies (PVT) Ltd,
15B Fullerton Estate II,
Gamagoda, Kalutara, Sri Lanka
---------------------------------------------------------------------------------- 
Author: Mr. Thurairajasingam Senthilruban   TSRuban[AT]mdsfoss.org
Consultant: Dr. Denham Pole                 DrPole[AT]gmail.com
URL: http: www.hhims.org
----------------------------------------------------------------------------------
*/

include_once 'mds_reporter/MDSReporter.php';
include_once '../class/MDSDataBase.php';
include_once '../mdsCore.php';
include_once '../class/MDSHospital.php';
require_once '../config.php';

$hospital = getHospital();
$pdf = new MDSReporter('P', 'mm', 'A5');
$pdf->addPage();

$from = $_GET['from'];
$to = $_GET['to'];
$visitType = $_GET['vtype'];
$sort = $_GET['sort'];
$from_date = new DateTime($_GET['from']);
$to_date = new DateTime($_GET['to']);


$visitTypes = array();
$where = '';
$pdf->writeTitle($hospital);
$pdf->writeSubTitle('Visit Complaints Treated From ' . $from_date->format('Y-m-d'). ' To ' . $to_date->format('Y-m-d'));
$pdf->Ln();

$link = mysql_connect(HOST, USERNAME, PASSWORD);
if (!$link) {
    die('Not connected : ' . mysql_error());
}

$db_selected = mysql_select_db(DB, $link);
if (!$db_selected) {
    die('Can\'t use foo : ' . mysql_error());
}

//date+1
date_add($to_date, new DateInterval('P1D'));
//get all visit types
if ($visitType == 'All') {
    $query = "select distinct `Name` from visit_type as vt,opd_visits as ov where ov.VisitType=vt.`Name` and ov.DateTimeOfVisit between '{$from_date->format('Y-m-d')}' and '{$to_date->format('Y-m-d')}'";
    $result = mysql_query($query);
    while ($row = mysql_fetch_array($result)) {
        array_push($visitTypes, $row['Name']);
    }
    mysql_free_result($result);
} else {
    array_push($visitTypes, $visitType);
}
//print_r($visitTypes);


//print_r($complaints);
//exit;

$orderBy = '';
switch ($sort) {
    case 'alpha':
        $orderBy = "order by `Name`";
        break;
    case 'freq':
        $orderBy = "order by cc desc,`Name`";
        break;

    default:
        $orderBy = "order by `Name`";
        break;
}

foreach ($visitTypes as $visitType) {
    
    $query = "select `Name`,count(`Name`) as cc from complaints as c,opd_visits as ov where ov.VisitType='{$visitType}' and ov.DateTimeOfVisit between '{$from_date->format('Y-m-d')}' and '{$to_date->format('Y-m-d')}' and (ov.Complaint like c.`Name` or ov.Complaint like concat(c.`Name`,',%') or ov.Complaint like concat('%,',c.`Name`,',%') or ov.Complaint like concat('%,',c.`Name`)) group by `Name` {$orderBy}";
    $result = mysql_query($query);
    $count = mysql_num_rows($result);
    if ($count > 0) {
        $pdf->SetWidths(array(128));
        $pdf->SetAligns(array('C'));
        $pdf->Row(array($visitType), true);
        $pdf->SetWidths(array(98, 30));
        $pdf->SetAligns(array('L', 'L'));
        $pdf->Row(array("Complaint Treated", "Number"), true);
        while ($row = mysql_fetch_array($result)) {
         $pdf->Row(array($row['Name'],$row['cc']));   
        }
    }
    
    mysql_free_result($result);
}
mysql_close($link);

//printf("Page was generated by PHP %s in %f seconds",phpversion(),$end-$start); 
$pdf->Output("visit_complaints_treated from $from to $to", 'I');
?>